### ISSUE TITLE
No docs/example on how to use snabbdom hooks.

### ISSUE THREAD

**Issue by delaneyj** [cerebral/cerebral-view-snabbdom#4]
Coming from React I'm missing the ability to use things like `didComponentMount`.  The snabbdom docs talk about insert/remove hooks.  How do you access this in cerebral-snabbdom components?

**Comment by christianalfoni** [comment]
Hi there, I have not tried them you, but they work like props of an element, it really has nothing to do with the component. So:

``` js
Component(({signals}) => (

  <div hook={{insert(vnode) { signals.appInserted(); }}>hey</div>

));
```

**Comment by christianalfoni** [comment]
I think it is more powerful as you can do it on any node actually.

**Comment by delaneyj** [comment]
Thanks for the clarification, I thought it would default to the props or attrs dictionary.
